name: Build 

on:
  push:
    branches:
    - main
  workflow_dispatch:

jobs:
  my_job:
    name: deploy to staging
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Build Solution
        run: msbuild .\PhysicsGame.sln /p:Configuration=Release

      - name: Create Artifact Directory
        run: mdkir artifact\PhysicsGame
        
     
